version: '3.8'

services:
  retailytics1:
    image: irl-ncai/deepstream:retailytics-v1
    stdin_open: true        # docker run -i
    tty: true        # docker run -t
    runtime: nvidia
    environment:
      DISPLAY: $DISPLAY
      NVIDIA_VISIBLE_DEVICES: all
      KAFKA_BROKER_IP: kafka1;19092
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: /bin/bash
    # ports:
    #   - "9092:9092"
    # depends_on:
    #   - kafka
