version: '3.8'

services:
  retailytics1:
    image: nvcr.io/nvidia/deepstream:v9-retailytics
    hostname: retailytics1
    runtime: nvidia
    environment:
      DISPLAY: $DISPLAY
      NVIDIA_VISIBLE_DEVICES: all
      KAFKA_BROKER_IP: kafka1;19092
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - "9092:9092"
    # depends_on:
    #   - kafka
