version: '3'

services:
  spark-worker-floor-processor-1:
    image: irl-ncai-retailytics/spark
    container_name: spark-worker-floor-processor-1
    command: spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.1.2 /opt/bitnami/spark/apps/analytics_generator.py
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_DAEMON_USER=spark
      - FLOOR_TOPIC=floor-raw-e9e5cb25-589e-4e4c-83c5-30fe584bad34
      - KAFKA_BROKER_IP=kafka1:19092
      - MONGO_DB_URL=mongodb
      - MONGO_DB_DATABASE=retail_analytics_db
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    volumes:
      - /home/sai/spark/checkpoints/:/opt/bitnami/spark/apps/checkpoints/

  spark-worker-floor-processor-2:
    image: irl-ncai-retailytics/spark
    container_name: spark-worker-floor-processor-2
    command: spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.1.2 /opt/bitnami/spark/apps/analytics_generator.py
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_DAEMON_USER=spark
      - FLOOR_TOPIC=floor-raw-e9e5cb25-589e-4e4c-83c5-30fe584bad3f
      - KAFKA_BROKER_IP=kafka1:19092
      - MONGO_DB_URL=mongodb
      - MONGO_DB_DATABASE=retail_analytics_db
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    volumes:
      - /home/sai/spark/checkpoints/:/opt/bitnami/spark/apps/checkpoints/
      # - /path/to/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
